on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.9, '3.10', '3.11' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        run: |
          pip install pdm

      - name: Install dependencies
        run: |
          pdm export --without-hashes -o requirements.txt 
          pip install -r requirements.txt
          pdm add .

      - name: Install browser
        run: playwright install

      - name: run pytest
        run: |
          pytest tests/test_run.py



