on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ '3.10' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install .

      - name: Install browser
        run: |
          playwright install --with-deps

      - name: run pytest
        run: |
          pytest tests/test_run.py



